config/routes.rb
SendGridInn::Application.routes.draw do

  root to: 'rooms#index'

  resources :rooms
  get 'users/new'
  resources :bookings, only: [:create, :destroy]
  
  resources :users, only: [:new, :create, :edit, :show, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete


end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :room_id, :start_date, :user_id, :stop_date
  
  validates_presence_of :room_id, :user_id, :stop_date, :start_date
  validate :start_date_cannot_be_in_the_past, :if => "!start_date.nil?"
  validate :stop_date_cannot_be_start_date, :if => "!start_date.nil? && !stop_date.nil?"
    
  belongs_to :room 
  belongs_to :user
  
  def start_date_cannot_be_in_the_past
    if start_date < Date.today && 
      errors.add(:start_date, "can't be in the past!")
    end
  end
  
  def stop_date_cannot_be_start_date
    if stop_date.to_date <= start_date.to_date
      errors.add(:stop_date, "booking must span at least one day!")
    end
  end
  
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :bed_count, :number

  validates_presence_of :bed_count, :number
  validates_uniqueness_of :number
  
  has_many :bookings
  
  def available?(user_start_date, user_stop_date)
    outcome = true
    self.bookings.each do |booking|
      #behold one UGLY chunk of code!
      dates_in_order = [user_start_date, user_stop_date, booking.start_date, booking.stop_date].sort
      dates_hash = Hash[dates_in_order.map.with_index.to_a]
      unless dates_hash[user_stop_date] - dates_hash[user_start_date] == 1 && dates_hash[booking.stop_date] - dates_hash[booking.start_date] == 1
        outcome = false
        next
      end
    end
    outcome
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :password_digest, :password, :password_confirmation

  validates_presence_of :email, :password, :password_confirmation
  validates_confirmation_of :password
  validates_uniqueness_of :email
  
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  include ApplicationHelper
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    booking = Booking.new(params[:booking])
    booking.user_id = session[:user_id]
    booking.stop_date = (params[:booking][:stop_date])
    puts booking.inspect
    if booking.save
      flash[:notice] = 'Booking made!'
      redirect_to user_path(session[:user_id])
    else
      flash[:error] = booking.errors.full_messages
      redirect_to rooms_path
    end
  end
  
  def destroy
    booking = Booking.find(params[:id])
    booking.destroy
    flash[:notice] = 'Booking cancelled!'
    redirect_to user_path(session[:user_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    if !session[:user_id]
      redirect_to '/signup'
    end
    @rooms = Room.all
    @start_date = params[:start_date] if params[:start_date]
    @stop_date = params[:stop_date] if params[:stop_date]
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      flash[:notice] = "Sign in successful!"
      redirect_to rooms_path
    else
      flash.now[:error] = 'Invalid email or password'
      render 'new'
    end
  end
  
  def destroy
    sign_out
    flash[:notice] = "Successfully signed out!"
    redirect_to signin_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Thank you for signing up!"
      session[:user_id] = @user.id
      redirect_to root_url
      
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def datetimed(time)
    date_array = time.split("/")
    date_time = Date.new(date_array[2].to_i,date_array[0].to_i,date_array[1].to_i).to_datetime
    date_time
  end

  def displaydated(date)
    day = date.day.to_s
    day = "0" + day if day.length < 2
    month = date.month.to_s
    month = "0" + month if month.length < 2
    day + "/" + month + "/" + date.year.to_s
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  
  def valid_date?(date)
    date =~ /\d{2}\/\d{2}\/\d{4}/
  end
  
  def availability(room)
    room.available?(datetimed(@start_date), datetimed(@stop_date)) ? "open" : "booked"
  end

  def date_errors(start_date, stop_date)
    errors = []
    if start_date && stop_date && !valid_date?(start_date) or !valid_date?(stop_date)
      errors << "Please enter dates in the format MM/DD/YYYY"
    end
    if start_date && datetimed(start_date) < Time.now.to_date
      errors << "Start date can't be in the past!"
    end
    #elsif datetimed(start_date) >= datetimed(stop_date)
    #  return ""
    errors
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end
  
  def sign_out
    self.current_user = nil
    session[:user_id] = nil
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      nil
    end
  end
  
  def signed_in?
    current_user != nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Send Grid Inn", '#', id: "logo" %>
    <nav>
      <ul class="nav pull-right">
        <li><%= link_to "Reservations", root_path %></li>

        <% if signed_in? %>
        <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
        <li><%= link_to "My Account", user_path(current_user) %></li>
        <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Send Grid Inn</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%=key%>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/rooms/index.html.erb
<h1>Reservations</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_tag rooms_path, method: 'get' do %>
      <%= label_tag "Start date" %>
      <%= text_field_tag :start_date, params[:start_date] %>
      <%= label_tag "End date" %>
      <%= text_field_tag :stop_date, params[:stop_date] %>
      <%= submit_tag "Search for rooms", :name => nil, class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
  <div class="span6 offset3">
    <% errors = date_errors(@start_date, @stop_date) %>
    <% if errors.count > 0 %>
      <h2>
        <% errors.each do |error| %>
          <%= error %>
        <% end %>
      </h2>
    <% else %>
      <h2>Room availability</h2>
      <table>
        <tr>
          <td>Room number</td>
          <td>Capacity</td>
          <td>Availability</td>
        </tr>
        <% @rooms.each do |room| %>
        <tr>
          <td><%= room.number %></td>
          <td><%= room.bed_count %></td>
          <td><%= availability(room) %></td>
          <td><%  if room.available?(datetimed(@start_date), datetimed(@stop_date)) %>
              <%= link_to 'book this room', bookings_path(booking: {start_date: datetimed(@start_date), stop_date: datetimed(@stop_date), room_id: room.id}), method: 'post',  class: "btn btn-large btn-primary"%>
              <% end %></td>
        </tr>
        <% end %>
      </table>
    <% end %>
  </div>  
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>
      
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.submit "create my account", class: "btn btn-large btn-primary" %>
      
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up for an account</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Your Account</h1>

<div class="row">
  <div class="span6 offset3">
    <% render 'form' %>
    <h2>Your bookings</h2>
    <table>
      <tr>
        <td>Room number</td>
        <td>Capacity</td>
        <td>Start date</td>
        <td>End date</td>
      </tr>
      <% @user.bookings.each do |booking| %>
      <tr>
        <td><%= booking.room.number %></td>
        <td><%= booking.room.bed_count %></td>
        <td><%= booking.start_date %></td>
        <td><%= booking.stop_date %></td>
        <td><%= link_to 'Cancel this booking', "/bookings/#{booking.id}", method: 'delete',  class: "btn btn-large btn-primary"%></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>